export const textConstants = {
    ONLY_MOBILE_VIEW : 'Sorry you need a phone to use the app.',
    WHO_WILL_WIN: 'Who will win the match?',
    TODAYS_MATCH: 'TODAY\'S MATCH',
    HOSTED_BY: 'Hosted by ',
    BETTING_ENDS: 'Betting ends in',
    BETTING_ENDED: 'Betting ended',
    MATCH_SOON : 'COMING SOON',
    TOMORROW: 'TOMORROW',
    GAME_ENDED: 'MATCH OVER',
    WELCOME_BACK: 'Welcome Back',
    JOINED_CONTEST: 'Congrats, for joining the Contest',
    AUTHENTICATION_FAILED: 'SingIn failed,Please try again.',
    OFFLINE: 'You are offline, Please wait',
    ONLINE: 'Back Online, Continue',
    TEAM_SELECTED: 'Team Selected',
    LOGOUT: 'Thank You, See you again',
    ERROR: 'Something went wrong, Please Try again',
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT"
}